name: Update Chart

on:
  push:
  schedule:
   - cron:  '0 7 * * *'

jobs:
  update-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      # - uses: r-lib/actions/setup-r@v2 # Optional with renv, mandatory with setup-r-dependencies
      #   with:
      #     r-version: 'renv'
      # - uses: r-lib/actions/setup-renv@v2 # If using Renv
      # - uses: r-lib/actions/setup-r@v2 # Optional with renv, mandatory with setup-r-dependencies
      - name: Create library
        run: dir.create(Sys.getenv("R_LIBS_USER"), recursive = TRUE) # So you don't have to run setup-r
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages: |
            any::dplyr
            any::ggplot2
            any::purrr
            any::lubridate
            any::svglite
            any::jsonlite
      # - name: Generate plot
      #   run: Rscript cpi_since_january_2020.R
      - name: Commit
        run: |
          git config --global user.name 'Wojtek Klimowicz'
          git config --global user.email 'Github@Actions'
          git add *
          git commit -m 'GH Actions Update ${{env.date}}' || echo "No changes to commit"
          git push || echo "No changes to commit"
